stages:
  - sync

variables:
  GITLAB_USER_EMAIL: trent.leslie@phenomehealth.org
  GITHUB_USER_EMAIL: trentleslie@gmail.com
  GIT_STRATEGY: clone
  GIT_DEPTH: 1

sync_gitlab_to_github:
  stage: sync
  image: python:3.10
  tags:
    - docker
  before_script:
    - git config --global user.email "$GITHUB_USER_EMAIL"
    - git config --global user.name "Trent Leslie"
    # Add the GitHub remote, replacing it if it exists
    - git remote remove github || true  # Remove if it exists, ignore errors if it does not
    - git remote add github https://$GITHUB_TOKEN@github.com/trentleslie/sparse-proteomic-prediction-of-common-and-rare-diseases.git
  script:
    - python --version
    - git fetch origin || exit 1
    - git checkout main || exit 1
    - git merge origin/main || exit 1
    - git push github main || exit 1
    - git push github main --tags || exit 1
  only:
    - main

